package com.telse.diary.utils;

/**
 * Created by telse on 25/01/17.
 */

public enum BaseHandlers {
    HANDLE_AUTHORIZATION_ERROR,
    HANDLE_AUTHORIZE,
    HANDLE_GET_LIST_PAGE_DATA,
    HANDLE_GET_WEB_PAGE_DATA,
    HANDLE_PICK_URL,
    HANDLE_GET_DISCUSSIONS_DATA,
    HANDLE_GET_DISCUSSION_LIST_DATA,
    HANDLE_JUST_DO_GET,
    HANDLE_DELETE_POST,
    HANDLE_EDIT_POST,
    HANDLE_DELETE_COMMENT,
    HANDLE_EDIT_COMMENT,
    HANDLE_UPLOAD_FILE,
    HANDLE_UPLOAD_MUSIC,
    HANDLE_UPLOAD_GIF,
    HANDLE_PRELOAD_THEMES,
    HANDLE_REPOST,
    HANDLE_QUERY_ONLINE,
    HANDLE_DELETE_POST_DRAFT,
    HANDLE_DELETE_TAG,
    HANDLE_REQUEST_DIARY
}
